master = Tk(className=' IdeaNebula - /New')
title = Label(master,text='New...                                            ',font='consolas 15',bg='#fff',fg='#707')
xtext = Label(master,text='Text',font='consolas 20',bg='#fff',fg='#0af')
xtext.bind('<ButtonRelease-1>',ideanebula_text)
xexit = Label(master,text='Exit',font='consolas 20',bg='#fff',fg='#f00')
xexit.bind('<ButtonRelease-1>',exit)
title.pack(side=TOP,fill=X)
xtext.pack(side=TOP,fill=X)
xexit.pack(side=TOP,fill=X)
master.mainloop()
